In [2]:
x = [1,2,3]
for i in x:
    print(i, end=',')
    

1,2,3,

In [3]:
import numpy as np

a = np.array([[1,2,3],[4,5,6]])
a[0,1] = 5
print(a)
print(a.shape) #rows, columns
print(a.ndim) #dimensions 
print(a.size)
print(a.dtype)

[[1 5 3]
 [4 5 6]]
(2, 3)
2
6
int32


In [54]:
m = np.random.randint(1,10,(10,3))
print(m)

[[8 1 5]
 [9 8 7]
 [1 4 5]
 [7 9 6]
 [2 9 9]
 [7 1 2]
 [5 3 6]
 [2 2 8]
 [7 9 6]
 [8 5 8]]


In [ ]:
row2_sum = np.sum(m[1,:])
row2_mean = np.mean(m[1,:])

print(f"Sum of 2nd row: {row2_sum}")
print(f"Mean of 2nd row: {row2_mean}")

Sum of 2nd row: 24
Mean of 2nd row: 8.0


In [59]:
row_sums = np.sum(m, axis=1)
row_means = np.mean(m, axis=1)

print(f"Sum of rows: {row_sums}")
print(f"Mean of rows: {row_means}")

Sum of rows: [14 24 10 22 20 10 14 12 22 21]
Mean of rows: [4.66666667 8.         3.33333333 7.33333333 6.66666667 3.33333333
 4.66666667 4.         7.33333333 7.        ]


In [63]:
column2_sum = np.sum(m[:,2])
column2_mean = column2_sum / m.shape[0]

print(f"Mean of 2nd column: {column2_mean}")

Mean of 2nd column: 6.2


In [66]:
v = [25, 16, 9, 4, 1]
sqr_roots = []
for i in v:
    sqr_roots.append(np.sqrt(i))

print("Square roots of the elements in the vector:", sqr_roots)

Square roots of the elements in the vector: [5.0, 4.0, 3.0, 2.0, 1.0]


In [69]:
def generate_vector(n):
    vector = np.array([i**2 for i in range(n,0,-1)])
    return vector

print(generate_vector(5))
print(generate_vector(10))
print(generate_vector(12))

[25 16  9  4  1]
[100  81  64  49  36  25  16   9   4   1]
[144 121 100  81  64  49  36  25  16   9   4   1]


In [76]:
m1 = np.zeros((4,5), dtype=int)
m1[:3,:3] = np.eye(3, dtype=int)
m1[:3, 3:] = np.full((3,2),2, dtype=int)
m1[3,:] = np.array([i**2 for i in range(5,0,-1)])

print(m1)

[[ 1  0  0  2  2]
 [ 0  1  0  2  2]
 [ 0  0  1  2  2]
 [25 16  9  4  1]]
